### ISSUE TITLE
Issue running with ImageJ headless

### ISSUE THREAD

**Issue by blidarescub** [Elphel/imagej-elphel#9]
Hello,
I get good results when using the Eclipse project and do the post processing from the GUI, but when I use the xml file generated by the GUI in a headless processing, it always says it processes just 3 out of 10 files but it finds 26 channels. While enumerating them, we see that the first file apparently has 12 channels (4 x 3 subchannels), second file as well and the third file only 2 channels.
The resulting pictures look good but some files are duplicated, although the image is very slightly different. I will attach here the output logs from the console.
Can you please advise on what am I possibly doing wrong?
The camera is Eyesis4Pi 393.
Thank you

=======
bogdan@bogdan-ProLiant-DL380p-Gen8:~/TURN/F0x06/Fiji.app$ ./ImageJ-linux64 --headless --mem 7150m --run Eyesis_Correction prefs=/processed_out/new.corr-xml
[INFO] Found 677 plugins.
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] Found 11 DataType plugins.
[INFO] Found 1 Platform plugins.
[INFO] Configuring platform: org.scijava.platform.DefaultPlatform
[INFO] Found 0 scripts
[INFO] Found 763 legacy plugins (plus 54 ignored).
[INFO] Found 22 InputWidget plugins.
Configuration parameters are restored from /processed_out/new.corr-xml
Read ADVANCED_MODE=false
Read MODE_3D=false
**Number of used channels: 26 ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 )**
Created vignetting info for channel 0 subchannel=0 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 0
Created vignetting info for channel 1 subchannel=0 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 1
Created vignetting info for channel 2 subchannel=0 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 2
Created vignetting info for channel 3 subchannel=0 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 3
Created vignetting info for channel 8 subchannel=1 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 8
Created vignetting info for channel 9 subchannel=1 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 9
Created vignetting info for channel 10 subchannel=1 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 10
Created vignetting info for channel 11 subchannel=1 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 11
Created vignetting info for channel 16 subchannel=2 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 16
Created vignetting info for channel 17 subchannel=2 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 17
Created vignetting info for channel 18 subchannel=2 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 18
Created vignetting info for channel 19 subchannel=2 (/tiles/1493702048_282484_1.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 19
Created vignetting info for channel 4 subchannel=0 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 4
Created vignetting info for channel 5 subchannel=0 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 5
Created vignetting info for channel 6 subchannel=0 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 6
Created vignetting info for channel 7 subchannel=0 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 7
Created vignetting info for channel 12 subchannel=1 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 12
Created vignetting info for channel 13 subchannel=1 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 13
Created vignetting info for channel 14 subchannel=1 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 14
Created vignetting info for channel 15 subchannel=1 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1944
No pixel defects info is available for channel 15
Created vignetting info for channel 20 subchannel=2 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1942
No pixel defects info is available for channel 20
Created vignetting info for channel 21 subchannel=2 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1942
No pixel defects info is available for channel 21
Created vignetting info for channel 22 subchannel=2 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1942
No pixel defects info is available for channel 22
Created vignetting info for channel 23 subchannel=2 (/tiles/1493702048_282484_2.jp4)
imageWidth= 2592 imageHeight=1942
No pixel defects info is available for channel 23
Created vignetting info for channel 24 subchannel=0 (/tiles/1493702048_282484_3.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 24
Created vignetting info for channel 25 subchannel=0 (/tiles/1493702048_282484_3.jp4)
imageWidth= 2592 imageHeight=1934
No pixel defects info is available for channel 25
**3 files to process (of 10), 26 images to process**
Processing channel 0 - subchannel 0 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Generating Lanczos kernel stack with A=3, oversampled=2, binsPerHalfPixel=50
Generated Lanczos kernel stack with A=3, oversampled=2, binsPerHalfPixel=50
Saving equirectangular result to /processed_out/1493702048_282484-00-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-00-DECONV-RGB24_EQR.tiff...
19:46:46.187 [Run$_main] DEBUG loci.common.NIOByteBufferProvider - Using mapped byte buffer? false
bytes.length=31644000
Done saving /processed_out/1493702048_282484-00-DECONV-RGB24_EQR.tiff
Processing image 1 (of 26) finished at 78.792 sec, --- Free memory=4246611648 (of 5212598272)
Processing channel 1 - subchannel 0 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-01-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-01-DECONV-RGB24_EQR.tiff...
bytes.length=31704000
Done saving /processed_out/1493702048_282484-01-DECONV-RGB24_EQR.tiff
Processing image 2 (of 26) finished at 148.418 sec, --- Free memory=4272506816 (of 5240549376)
Processing channel 2 - subchannel 0 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-02-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-02-DECONV-RGB24_EQR.tiff...
bytes.length=31932000
Done saving /processed_out/1493702048_282484-02-DECONV-RGB24_EQR.tiff
Processing image 3 (of 26) finished at 215.727 sec, --- Free memory=4275183376 (of 5240549376)
Processing channel 3 - subchannel 0 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-03-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-03-DECONV-RGB24_EQR.tiff...
bytes.length=32076000
Done saving /processed_out/1493702048_282484-03-DECONV-RGB24_EQR.tiff
Processing image 4 (of 26) finished at 283.190 sec, --- Free memory=4275186456 (of 5240549376)
Processing channel 8 - subchannel 1 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-08-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-08-DECONV-RGB24_EQR.tiff...
bytes.length=22073088
Done saving /processed_out/1493702048_282484-08-DECONV-RGB24_EQR.tiff
Processing image 5 (of 26) finished at 350.644 sec, --- Free memory=4275193096 (of 5240549376)
Processing channel 9 - subchannel 1 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-09-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-09-DECONV-RGB24_EQR.tiff...
bytes.length=21825528
Done saving /processed_out/1493702048_282484-09-DECONV-RGB24_EQR.tiff
Processing image 6 (of 26) finished at 417.667 sec, --- Free memory=4275193456 (of 5240549376)
Processing channel 10 - subchannel 1 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-10-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-10-DECONV-RGB24_EQR.tiff...
bytes.length=21886312
Done saving /processed_out/1493702048_282484-10-DECONV-RGB24_EQR.tiff
Processing image 7 (of 26) finished at 484.701 sec, --- Free memory=4275193312 (of 5240549376)
Processing channel 11 - subchannel 1 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-11-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-11-DECONV-RGB24_EQR.tiff...
bytes.length=21725040
Done saving /processed_out/1493702048_282484-11-DECONV-RGB24_EQR.tiff
Processing image 8 (of 26) finished at 551.951 sec, --- Free memory=4275193152 (of 5240549376)
Processing channel 16 - subchannel 2 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-16-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-16-DECONV-RGB24_EQR.tiff...
bytes.length=31716000
Done saving /processed_out/1493702048_282484-16-DECONV-RGB24_EQR.tiff
Processing image 9 (of 26) finished at 622.076 sec, --- Free memory=4275286784 (of 5240549376)
Processing channel 17 - subchannel 2 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-17-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-17-DECONV-RGB24_EQR.tiff...
bytes.length=31452000
Done saving /processed_out/1493702048_282484-17-DECONV-RGB24_EQR.tiff
Processing image 10 (of 26) finished at 692.930 sec, --- Free memory=4275308560 (of 5240549376)
Processing channel 18 - subchannel 2 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-18-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-18-DECONV-RGB24_EQR.tiff...
bytes.length=31260000
Done saving /processed_out/1493702048_282484-18-DECONV-RGB24_EQR.tiff
Processing image 11 (of 26) finished at 764.231 sec, --- Free memory=4275308432 (of 5240549376)
Processing channel 19 - subchannel 2 of /tiles/1493702048_282484_1.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-19-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-19-DECONV-RGB24_EQR.tiff...
bytes.length=31764000
Done saving /processed_out/1493702048_282484-19-DECONV-RGB24_EQR.tiff
Processing image 12 (of 26) finished at 836.152 sec, --- Free memory=4275286216 (of 5240549376)
Processing channel 4 - subchannel 0 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Cutting result image in two parts to prevent roll-over
Saving equirectangular result to /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-LEFT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-LEFT.tiff...
bytes.length=16408360
Done saving /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-LEFT.tiff
Saving equirectangular result to /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-RIGHT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-RIGHT.tiff...
bytes.length=15247640
Done saving /processed_out/1493702048_282484-04-DECONV-RGB24_EQR-RIGHT.tiff
Processing image 13 (of 26) finished at 900.797 sec, --- Free memory=4275272672 (of 5240549376)
Processing channel 5 - subchannel 0 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-05-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-05-DECONV-RGB24_EQR.tiff...
bytes.length=31440000
Done saving /processed_out/1493702048_282484-05-DECONV-RGB24_EQR.tiff
Processing image 14 (of 26) finished at 964.907 sec, --- Free memory=4275286544 (of 5240549376)
Processing channel 6 - subchannel 0 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-06-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-06-DECONV-RGB24_EQR.tiff...
bytes.length=31632000
Done saving /processed_out/1493702048_282484-06-DECONV-RGB24_EQR.tiff
Processing image 15 (of 26) finished at 1031.641 sec, --- Free memory=4275285840 (of 5240549376)
Processing channel 7 - subchannel 0 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-07-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-07-DECONV-RGB24_EQR.tiff...
bytes.length=31992000
Done saving /processed_out/1493702048_282484-07-DECONV-RGB24_EQR.tiff
Processing image 16 (of 26) finished at 1098.503 sec, --- Free memory=4275286424 (of 5240549376)
Processing channel 12 - subchannel 1 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Cutting result image in two parts to prevent roll-over
Saving equirectangular result to /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-LEFT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-LEFT.tiff...
bytes.length=11290656
Done saving /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-LEFT.tiff
Saving equirectangular result to /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-RIGHT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-RIGHT.tiff...
bytes.length=10307040
Done saving /processed_out/1493702048_282484-12-DECONV-RGB24_EQR-RIGHT.tiff
Processing image 17 (of 26) finished at 1163.895 sec, --- Free memory=4275181272 (of 5240549376)
Processing channel 13 - subchannel 1 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-13-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-13-DECONV-RGB24_EQR.tiff...
bytes.length=21700164
Done saving /processed_out/1493702048_282484-13-DECONV-RGB24_EQR.tiff
Processing image 18 (of 26) finished at 1229.294 sec, --- Free memory=4275191856 (of 5240549376)
Processing channel 14 - subchannel 1 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-14-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-14-DECONV-RGB24_EQR.tiff...
bytes.length=21800556
Done saving /processed_out/1493702048_282484-14-DECONV-RGB24_EQR.tiff
Processing image 19 (of 26) finished at 1295.066 sec, --- Free memory=4275190912 (of 5240549376)
Processing channel 15 - subchannel 1 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-15-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-15-DECONV-RGB24_EQR.tiff...
bytes.length=21735880
Done saving /processed_out/1493702048_282484-15-DECONV-RGB24_EQR.tiff
Processing image 20 (of 26) finished at 1360.391 sec, --- Free memory=4275192760 (of 5240549376)
Processing channel 20 - subchannel 2 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Cutting result image in two parts to prevent roll-over
Saving equirectangular result to /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-LEFT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-LEFT.tiff...
bytes.length=16357440
Done saving /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-LEFT.tiff
Saving equirectangular result to /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-RIGHT.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-RIGHT.tiff...
bytes.length=15322560
Done saving /processed_out/1493702048_282484-20-DECONV-RGB24_EQR-RIGHT.tiff
Processing image 21 (of 26) finished at 1436.545 sec, --- Free memory=4275190184 (of 5240549376)
Processing channel 21 - subchannel 2 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-21-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-21-DECONV-RGB24_EQR.tiff...
bytes.length=31800000
Done saving /processed_out/1493702048_282484-21-DECONV-RGB24_EQR.tiff
Processing image 22 (of 26) finished at 1512.422 sec, --- Free memory=4275202720 (of 5240549376)
Processing channel 22 - subchannel 2 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-22-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-22-DECONV-RGB24_EQR.tiff...
bytes.length=31656000
Done saving /processed_out/1493702048_282484-22-DECONV-RGB24_EQR.tiff
Processing image 23 (of 26) finished at 1587.491 sec, --- Free memory=4275223952 (of 5240549376)
Processing channel 23 - subchannel 2 of /tiles/1493702048_282484_2.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-23-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-23-DECONV-RGB24_EQR.tiff...
bytes.length=31968000
Done saving /processed_out/1493702048_282484-23-DECONV-RGB24_EQR.tiff
Processing image 24 (of 26) finished at 1660.761 sec, --- Free memory=4275202488 (of 5240549376)
Processing channel 24 - subchannel 0 of /tiles/1493702048_282484_3.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-24-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-24-DECONV-RGB24_EQR.tiff...
bytes.length=21696200
Done saving /processed_out/1493702048_282484-24-DECONV-RGB24_EQR.tiff
Processing image 25 (of 26) finished at 1734.437 sec, --- Free memory=4275295768 (of 5240549376)
Processing channel 25 - subchannel 0 of /tiles/1493702048_282484_3.jp4
Will scale intensity (to compensate for exposure) by  0.7309322033898304
Saving equirectangular result to /processed_out/1493702048_282484-25-DECONV-RGB24_EQR.tiff
Saving 8-bit TIFF with alpha-channel: /processed_out/1493702048_282484-25-DECONV-RGB24_EQR.tiff...
bytes.length=21938772
Done saving /processed_out/1493702048_282484-25-DECONV-RGB24_EQR.tiff
Processing image 26 (of 26) finished at 1808.851 sec, --- Free memory=4275294592 (of 5240549376)

**Comment by okdzhimiev** [comment]
The [version with Eyesis4Pi393 support](https://git.elphel.com/Elphel/imagej-elphel/tree/v1.1) was missing changes for headless run.
Created a new branch [here](https://git.elphel.com/Elphel/imagej-elphel/tree/eyesis4pi393)
